name: Check Lint

on:
  push:
    branches:
      - feat*
    paths:
      - 'src/**'
      - 'biome.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install Dependencies
        run: npm install

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint
